import requests

url = "https://botometer-pro.p.rapidapi.com/litev1/check_accounts_in_bulk"

payload = [
	{
		"contributors": None,
		"coordinates": None,
		"created_at": "Wed Jun 05 21:42:20 +0000 2019",
		"favorite_count": 0,
		"favorited": False,
		"geo": None,
		"id": 1234,
		"id_str": "1234",
		"in_reply_to_screen_name": None,
		"in_reply_to_status_id": None,
		"in_reply_to_status_id_str": None,
		"in_reply_to_user_id": None,
		"in_reply_to_user_id_str": None,
		"is_quote_status": False,
		"lang": "en",
		"place": None,
		"retweet_count": 0,
		"retweeted": False,
		"text": "this is the tweet text",
		"truncated": True,
		"user": {
			"contributors_enabled": False,
			"created_at": "Fri Mar 02 02:27:13 +0000 2018",
			"default_profile": False,
			"default_profile_image": False,
			"description": "Description",
			"favourites_count": 2,
			"follow_request_sent": False,
			"followers_count": 23,
			"following": False,
			"friends_count": 8,
			"geo_enabled": False,
			"has_extended_profile": True,
			"id": 1111,
			"id_str": "1111",
			"is_translation_enabled": False,
			"is_translator": False,
			"lang": None,
			"listed_count": 1,
			"location": "Location",
			"name": "User name",
			"notifications": False,
			"profile_background_color": "000000",
			"profile_background_image_url": "url",
			"profile_background_image_url_https": "url",
			"profile_background_tile": False,
			"profile_banner_url": "url",
			"profile_image_url": "url",
			"profile_image_url_https": "url",
			"profile_link_color": "000000",
			"profile_sidebar_border_color": "000000",
			"profile_sidebar_fill_color": "000000",
			"profile_text_color": "000000",
			"profile_use_background_image": False,
			"protected": False,
			"screen_name": "user screen_name",
			"statuses_count": 3792,
			"time_zone": None,
			"translator_type": "none",
			"url": "url",
			"utc_offset": None,
			"verified": False
		}
	},
	{
		"contributors": None,
		"coordinates": None,
		"created_at": "Wed Jun 10 21:42:20 +0000 2019",
		"favorite_count": 0,
		"favorited": False,
		"geo": None,
		"id": 12345,
		"id_str": "12345",
		"in_reply_to_screen_name": None,
		"in_reply_to_status_id": None,
		"in_reply_to_status_id_str": None,
		"in_reply_to_user_id": None,
		"in_reply_to_user_id_str": None,
		"is_quote_status": False,
		"lang": "en",
		"place": None,
		"retweet_count": 0,
		"retweeted": False,
		"text": "this is the tweet text",
		"truncated": True,
		"user": {
			"contributors_enabled": False,
			"created_at": "Fri Mar 02 02:27:13 +0000 2018",
			"default_profile": False,
			"default_profile_image": False,
			"description": "Description",
			"favourites_count": 2,
			"follow_request_sent": False,
			"followers_count": 2321,
			"following": False,
			"friends_count": 82,
			"geo_enabled": False,
			"has_extended_profile": True,
			"id": 2222,
			"id_str": "2222",
			"is_translation_enabled": False,
			"is_translator": False,
			"lang": None,
			"listed_count": 112,
			"location": "Location",
			"name": "User name",
			"notifications": False,
			"profile_background_color": "000000",
			"profile_background_image_url": "url",
			"profile_background_image_url_https": "url",
			"profile_background_tile": False,
			"profile_banner_url": "url",
			"profile_image_url": "url",
			"profile_image_url_https": "url",
			"profile_link_color": "000000",
			"profile_sidebar_border_color": "000000",
			"profile_sidebar_fill_color": "000000",
			"profile_text_color": "000000",
			"profile_use_background_image": False,
			"protected": False,
			"screen_name": "user screen_name",
			"statuses_count": 372,
			"time_zone": None,
			"translator_type": "none",
			"url": "url",
			"utc_offset": None,
			"verified": False
		}
	}
]
headers = {
	"content-type": "application/json",
	"X-RapidAPI-Key": "SIGN-UP-FOR-KEY",
	"X-RapidAPI-Host": "botometer-pro.p.rapidapi.com"
}

response = requests.request("POST", url, json=payload, headers=headers)

print(response.text)